//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoFinal : DbContext
    {
        public ProyectoFinal()
            : base("name=ProyectoFinal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OFFICE> OFFICE { get; set; }
        public virtual DbSet<OFFICE_DETAIL> OFFICE_DETAIL { get; set; }
        public virtual DbSet<USER_OFFICE> USER_OFFICE { get; set; }
    }
}
