//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFICE_DETAIL
    {
        public int ID_DETAIL { get; set; }
        public System.DateTime DATE_DETAIL { get; set; }
        public int ID_USER_DETAIL { get; set; }
        public string LOCATION_DETAIL { get; set; }
    
        public virtual USER_OFFICE USER_OFFICE { get; set; }
    }
}
